### ISSUE TITLE
libghttp怎么进行交叉编译

### ISSUE THREAD

**Issue by XinrongHuang** [jemygraw/libghttp-qiniu#2]
我尝试了交叉编译几次，都是到链接的地方就出错了，能否告知一下交叉编译的命令或步骤？

**Comment by jemygraw** [comment]
看看是不是README里面的错误。

**Comment by XinrongHuang** [comment]
我看README里面的编译步骤，并没有指定交叉工具链，这样放到arm主板上能运行吗？

**Comment by jemygraw** [comment]
我之前在树莓派上面编译过，是可以运行的。但是我没有搞过交叉编译。树莓派的CPU是arm的。
